### ISSUE TITLE
Can MPRAflow deal with this type of MPRA data?

### ISSUE THREAD

**Issue by Sylarair** [shendurelab/MPRAflow#27]
Hi,

I am dealing with MPRA data with `MPRAflow`, however, I am gonna process this kind of MPRA dataset ([https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE87711](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE87711)), which lacks insert sequence, barcode, and element sequence fa. 

So, my question is: can MPRAflow deal with this dataset? I have tried several times but failed. Could anyone help me with this? Thanks!

**Comment by makirc** [comment]
Dear Sylarair,
 
This is a little confusing. It seems the referenced data set has changed in this issue. You previously referred to https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE142207, which is STARR-seq  data. While used for similar biological questions, MPRA and STARR-seq assays are very different in the kind of data that is obtained. For STARR-Seq the analysis is more similar to a ChIP-seq approach where you are measuring peak height over control. In contrast, MPRAs are measuring RNA/DNA ratios corresponding to pre-assigned regulatory sequence candidates. MPRAflow is therefore not appropriate for the analysis of such kind of data. Please look around for something else. I just saw this pre-print: https://www.biorxiv.org/content/10.1101/694869v3 Maybe this is a good starting point for you. I also noticed a bioconductor package (https://bioconductor.org/packages/release/bioc/html/BasicSTARRseq.html).

You now changed to an actual MPRA data set (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE87711). This data set references two files: GSE87711_design.txt.gz and GSE87711_design_barcodes.txt.gz which should provide you with the relevant assignment of barcodes to candidate sequences. The whole data set might be a little tricky though, because RNA and DNA samples are not strictly matched here, i.e. you do not have RNA for every DNA sample, but you only get DNA count representations from sequencing of the plasmid library prior to the transfections. You would need to calculate RNA/DNA from these values as proxy for what made it into the the cells. Further the number of replicates varies for the different experiments. This is all not ideal. You might consider pooling the two DNA samples as well as RNA samples of the same condition.

Hope that helps. 

Best,
Martin

**Comment by Sylarair** [comment]
Thanks! I realized that dataset I pasted before was STARR-seq, so I changed it to MPRA which I focused on. 

By the way, I am still confused about how to apply MPRAflow to such MPRA dataset including GSE87711 and [https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE115042](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE115042). If possible, could you give me some advice such as code?

**Comment by Sylarair** [comment]
The fastq was splited into 4 files, and the *_1, *_2.fastq.gz has length 100, while *_3, *_4.fastq.gz has length 12, 6.

<img width="844" alt="Screen Shot 2020-06-01 at 9 48 55 AM" src="https://user-images.githubusercontent.com/18133362/83368924-1ef26480-a3ed-11ea-9b26-abe741269df3.png">

**Comment by Sylarair** [comment]
<img width="833" alt="Screen Shot 2020-06-01 at 10 01 40 AM" src="https://user-images.githubusercontent.com/18133362/83369420-e5baf400-a3ee-11ea-89e4-83784f89117c.png">

<img width="682" alt="Screen Shot 2020-06-01 at 10 01 50 AM" src="https://user-images.githubusercontent.com/18133362/83369426-eb183e80-a3ee-11ea-8029-8344e5f4586c.png">

**Comment by visze** [comment]
cleaning up. please reopen if still an issue
