### ISSUE TITLE
Error running association utility

### ISSUE THREAD

**Issue by tjflem** [shendurelab/MPRAflow#33]
Hello, I am trying to run the association utility on my own data set and am receiving this error: 
![8c6ca03686008bed737af2e0b5cfe8bb](https://user-images.githubusercontent.com/73509048/108630812-c3fa1500-7434-11eb-83f5-5ed5168b0435.png)

I have been closely following the protocol, and here is my code: 
nextflow run association.nf -w /home/tfleming/Desktop/Assoc_Basic/data/work --fastq-insert "/home/tfleming/Desktop/Assoc_Basic/data/MPRA_Library_Files/Trimmed_Undetermined_S0_L001_R1_001.fastq" --fastq-insertPE "/home/tfleming/Desktop/Assoc_Basic/data/MPRA_Library_Files/Trimmed_Undetermined_S0_L001_R2_001.fastq" --fastq-bc "/home/tfleming/Desktop/Assoc_Basic/data/MPRA_Library_Files/Trimmed_Undetermined_S0_L001_I1_001.fastq" --design "/home/tfleming/Desktop/Assoc_Basic/data/MPRA_Library_Files/MPRAFlow_Association_Design.fa" --name assoc_basic

Thank you!

**Comment by visze** [comment]
From your screenshot it looks that everything before "filter_barcodes" works fine. But I do not trust this output. I think the issue is before and you get "empty files". Then finally it failes at the end.

Are you are familiar with nextflow? For debugging what step goes wrong you have to go to your work directory, then follow the hashed folders from nextflow per step (e.g. ce/fdd7e7 for count_bc_nolab) and look at the files. Do you have empty outputs? Makes the outpunt sense... etc. 

First I would start with the last (failing step) and look at the input files. These are `${name}_barcodes_per_candidate-no_repeats-no_jackpots.feather` and `label_rmIllegalChars.txt`. 
If they look suspicious (e.g. are empty) I would start from the beginning and go stepwise down.

**Comment by visze** [comment]
We resolved this issue via email.

Here is the solution for documentation.

- Creating the `--design` fasta file in windows introduces strange characters at line breaks. Without using a label files these line beraks are in the default label file and then it breaks. To resolv this use a label file or use unix system for cretaing the design file. I will add a fix in the future to filter out these characters.
- @tjflem uses 271 bp oligos so we have to use `--cigar 271M`
- When you have very similar sequences (e.g. when using SNVs: ref/alt) the mapping quality drops (because first and secodn alignment are close. This is independent of the `--cigar` option. So you have to reduce the mapping quality. e.g. with the cigar option it mitght be ok to use `--mapq 0` or `--mapq 1`
