### ISSUE TITLE
Expected barcode promiscuousness

### ISSUE THREAD

**Issue by roryk** [shendurelab/MPRAflow#44]
Hi everyone! Thanks for publishing such a nice pipeline. When doing the barcode association, do you have a rule of thumb regarding what is an acceptable level of barcodes mapping to more than one candidate sequence? We've had ranges from 2% up to 16% using 25 base barcodes-- would the higher end of that range give you pause? If not, at what point would you worry that the protocol needed to be optimized? Thank you!

**Comment by makirc** [comment]
Hi Rory, Thank you for your message and nice words. There is always some ambiguity in the barcodes, for example because some low complexity sequences are more easily synthesized and therefore more abundant, but also because of some readout issues that may look like barcode but are created from adapters or failed sequence readouts (G stretches for NextSeq instruments). At 25 base pair length, 16% would worry me and I would look closely at the specific design and experimental steps. In a recent experiment with a large pool of shorte barcodes (15 bp and about 20M barcodes observed at least three times, giving just a random collision at 1.9%), 2M (~10%) do not have informative or full-length alignments of the insert, less than 1 M (5%) has multiple associated insert sequences and 85% are unambiguous assignments. Hope that helps.

**Comment by roryk** [comment]
Thanks so much @makirc for sharing your knowledge, knowing the ambiguous barcode percentage was high helped us narrow down our issue and fix it.
