### ISSUE TITLE
failed at calc_correlations step

### ISSUE THREAD

**Issue by xunchen85** [shendurelab/MPRAflow#50]
Hi Max,

When I ran count.nf function, I stuck at this step with the error of outputing *.png files. Following the messages, I was able to successfully run the Rscript independently and obtain corresponding correlation.txt and multiple png files as I attached. 

I want to double-check with you whether I missed other downstream steps with this error? Do I really need to debug this error about outputting figures in the pipeline?

Thanks,
Xun

![image](https://user-images.githubusercontent.com/9758589/126442306-6c8a67a1-c973-4ac5-bbf7-8178007d952e.png)
![image](https://user-images.githubusercontent.com/9758589/126443077-aa5587c1-4808-4ddf-b522-3c7ba8926cfa.png)

**Comment by visze** [comment]
Hi xun,

Sorry that your run into an error again.  Calc correlation and make rnaster
tables are the last steps. So it seems to be ok.


Maybe it is a runtime error. Creating these plots take sometimes ages an
the job got killed. You can change the label to longtime here:
https://github.com/shendurelab/MPRAflow/blob/3df34853904e0245507a361c700791c3e49a7e0e/count.nf#L607

Maybe this helps. But anyway you should have all the output files of the
count workflow because you run the script by yourself.

Best,
Max


Xun Chen ***@***.***> schrieb am Mi., 21. Juli 2021, 08:41:

**Comment by xunchen85** [comment]
Hi Max,

Thanks for your prompt reply. I guess the error is due to the Cairo, which I did not successfully set up in the environment. I tried but it failed. Anyhow, I'm glad it went through. 

Thanks for your confirmation.

Best,
Xun
